apiVersion: v1
kind: Service
metadata:
  name: streamflix-metrics-svc
  labels:
    app: streamflix-metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: streamflix-metrics
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030 
      